In [3]:
# Student Performance Data Analysis Using NumPy

# 1. Import NumPy

import numpy as np


# 2. Load the Dataset

study_data = np.genfromtxt(
    '/content/sample_data/study_data.csv',
    delimiter=',',
    skip_header=1
)

print("Dataset:")
print(study_data)


# 3. Extract Important Features

study_hours = study_data[:, 0]
attendance = study_data[:, 1]
score = study_data[:, 2]

print("\nStudy Hours:", study_hours)
print("Attendance:", attendance)
print("Score:", score)


# 4. Inspect the Dataset

print("\n--- Dataset Information ---")

print("Dimensions:", study_data.ndim)
print("Total elements:", study_data.size)
print("Data type:", study_data.dtype)
print("Shape:", study_data.shape)


# 5. Create Small Test Arrays

zeros_1d = np.zeros(2)
zeros_2d = np.zeros((2, 3))
range_array = np.arange(1, 6)
linear_array = np.linspace(1, 10, 5)

print("\nZeros 1D:")
print(zeros_1d)

print("\nZeros 2D:")
print(zeros_2d)

print("\nArange:")
print(range_array)

print("\nLinspace:")
print(linear_array)


# 6. Indexing and Slicing

print("\nFirst row:")
print(study_data[0])

print("\nScore column:")
print(study_data[:, 2])

print("\nSecond row:")
print(study_data[1])

print("\nAttendance column:")
print(study_data[:, 1])

print("\nValues from row index 2, columns 1 and 2:")
print(study_data[2, 1:3])

print("\nFirst 5 Study Hours:")
print(study_data[:5, 0])


# 7. Reshaping, Flatten and Ravel

print("\nStudy Hours reshaped:")
print(study_hours.reshape(4, 2))

print("\nScore reshaped:")
print(score.reshape(2, 4))

reshaped_attendance = attendance.reshape(4, 2)

print("\nAttendance reshaped:")
print(reshaped_attendance)

print("\nFlatten:")
print(reshaped_attendance.flatten())

print("\nRavel:")
print(reshaped_attendance.ravel())

# 8. Statistical Analysis

print("\nMean:", study_data.mean())
print("Median:", np.median(study_data))
print("Sum:", study_data.sum())
print("Variance:", study_data.var())
print("Standard Deviation:", study_data.std())
print("Minimum:", study_data.min())
print("Maximum:", study_data.max())


# 9. Row-wise and Column-wise Operations

print("\nMean of each row:")
print(study_data.mean(axis=1))

print("\nMaximum of each row:")
print(study_data.max(axis=1))

print("\nSum of each row:")
print(study_data.sum(axis=1))

print("\nMean of each feature:")
print(study_data.mean(axis=0))

print("\nMinimum of each feature:")
print(study_data.min(axis=0))


# 10. Boolean Indexing and Filtering

test_array = np.array([12, 52, 63, 45, 87])

print("\nValues greater than 50:")
print(test_array[test_array > 50])

print("\nValues greater than dataset mean:")
print(study_data[study_data > study_data.mean()])

print("\nValues less than dataset mean:")
print(study_data[study_data < study_data.mean()])

print("\nValues between 20 and 80:")
print(study_data[(study_data > 20) & (study_data < 80)])


# 11. Conditional Categorization

result = np.where(score > 50, "Pass", "Fail")

print("\nPass / Fail:")
print(result)

categories = np.select(
    [
        score > 80,
        score > 60,
        score > 50
    ],
    [
        "High",
        "Medium-High",
        "Medium"
    ],
    default="Low"
)

print("\nScore Categories:")
print(categories)


# 12. Sorting and Ranking

study_hours_original = study_hours.copy()

print("\nStudy Hours in ascending order:")
print(np.sort(study_hours))

print("\nStudy Hours in descending order:")
print(np.sort(study_hours)[::-1])

print("\nTop 5 values in the complete dataset:")
print(np.sort(study_data.flatten())[::-1][:5])

print("\nBottom 5 values in the complete dataset:")
print(np.sort(study_data.flatten())[:5])

print("\nIndex of highest Attendance:")
print(attendance.argmax())

print("\nScore indexes in ascending order:")
print(score.argsort())

print("\nStudy Hours indexes ranked in descending order:")
print(study_hours_original.argsort()[::-1])


# 13. Stacking and Concatenation

print("\nVertical Stacking:")
print(np.vstack((attendance, score)))

print("\nHorizontal Stacking:")
print(np.hstack((attendance, score)))

print("\nConcatenation:")
print(np.concatenate((attendance, score)))


# 14. Vectorization

print("\nAttendance + 2:")
print(attendance + 2)

print("\nScore × 2:")
print(score * 2)

print("\nAttendance - Score:")
print(attendance - score)


# 15. Broadcasting

column_adjustment = np.array([1, 2, 2])

print("\nColumn-wise Broadcasting:")
print(study_data + column_adjustment)

row_adjustment = np.array(
    [1, 2, 3, 5, 1, 2, 6, 4]
).reshape(8, 1)

print("\nRow-wise Broadcasting:")
print(study_data + row_adjustment)


# 16. Data Cleaning

modified_data = study_data.copy()

# Add a missing value
modified_data[1, 1] = np.nan

# Add an invalid attendance value
modified_data[2, 1] = 150

print("\nModified Dataset:")
print(modified_data)


# Detect Missing Values

missing_mask = np.isnan(modified_data)

print("\nMissing Value Mask:")
print(missing_mask)

print("\nAre there missing values?")
print(missing_mask.any())

print("\nMissing Value Position:")
print(np.where(missing_mask))


# Detect Invalid Values

attendance_modified = modified_data[:, 1]

invalid_mask = (
    (attendance_modified < 0) |
    (attendance_modified > 100)
)

print("\nInvalid Attendance Values:")
print(attendance_modified[invalid_mask])

print("\nInvalid Value Position:")
print(np.where(invalid_mask))


# Replace Missing and Invalid Values

modified_data[np.isnan(modified_data)] = 0

print("\nAfter Replacing Missing Values:")
print(modified_data)

attendance_modified = modified_data[:, 1]

invalid_mask = (
    (attendance_modified < 0) |
    (attendance_modified > 100)
)

attendance_modified[invalid_mask] = 0

print("\nAfter Replacing Invalid Values:")
print(modified_data)


# 17. Random Data Generation

test_data = np.random.randint(0, 100, (5, 3))

print("\nRandom Data:")
print(test_data)

np.random.shuffle(test_data)

print("\nShuffled Data:")
print(test_data)

np.random.seed(5)

fixed_data = np.random.randint(0, 100, (5, 3))

print("\nRandom Data with Fixed Seed:")
print(fixed_data)


# 18. Basic Linear Algebra

vector = np.array([1, 2, 3])

print("\nVector:")
print(vector)

A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print("\nTranspose of A:")
print(A.T)

print("\nMatrix Multiplication:")
print(A @ B)

print("\nDot Product of Matrices:")
print(np.dot(A, B))

v1 = np.array([5, 6, 2, 3, 4])
v2 = np.array([2, 3, 4, 7, 2])

print("\nDot Product of Vectors:")
print(np.dot(v1, v2))

print("\nElement-wise Multiplication:")
print(A * B)


# 19. Final Analysis and Insights

features = np.array([
    "Study Hours",
    "Attendance",
    "Score"
])

feature_means = study_data.mean(axis=0)

print("\nAverage of Each Feature:")

for feature, mean in zip(features, feature_means):
    print(f"{feature}: {mean:.2f}")

highest_average_feature = features[np.argmax(feature_means)]

print("\nFeature with the Highest Average:")
print(highest_average_feature)

feature_variance = study_data.var(axis=0)

highest_variation_feature = features[
    np.argmax(feature_variance)
]

print("\nFeature with the Highest Variation:")
print(highest_variation_feature)

highest_score_index = np.argmax(score)

print("\nRecord with the Highest Score:")
print("Row:", highest_score_index)
print("Score:", score[highest_score_index])



Dataset:
[[ 5. 65. 78.]
 [ 3. 54. 45.]
 [ 6. 70. 40.]
 [ 4. 90. 52.]
 [ 7. 85. 80.]
 [ 8. 95. 91.]
 [ 6. 75. 85.]
 [ 4. 60. 65.]]

Study Hours: [5. 3. 6. 4. 7. 8. 6. 4.]
Attendance: [65. 54. 70. 90. 85. 95. 75. 60.]
Score: [78. 45. 40. 52. 80. 91. 85. 65.]

--- Dataset Information ---
Dimensions: 2
Total elements: 24
Data type: float64
Shape: (8, 3)

Zeros 1D:
[0. 0.]

Zeros 2D:
[[0. 0. 0.]
 [0. 0. 0.]]

Arange:
[1 2 3 4 5]

Linspace:
[ 1.    3.25  5.5   7.75 10.  ]

First row:
[ 5. 65. 78.]

Score column:
[78. 45. 40. 52. 80. 91. 85. 65.]

Second row:
[ 3. 54. 45.]

Attendance column:
[65. 54. 70. 90. 85. 95. 75. 60.]

Values from row index 2, columns 1 and 2:
[70. 40.]

First 5 Study Hours:
[5. 3. 6. 4. 7.]

Study Hours reshaped:
[[5. 3.]
 [6. 4.]
 [7. 8.]
 [6. 4.]]

Score reshaped:
[[78. 45. 40. 52.]
 [80. 91. 85. 65.]]

Attendance reshaped:
[[65. 54.]
 [70. 90.]
 [85. 95.]
 [75. 60.]]

Flatten:
[65. 54. 70. 90. 85. 95. 75. 60.]

Ravel:
[65. 54. 70. 90. 85. 95. 75. 60.]

Mean: 48.87